version: 1
services:
  - type: web
    name: viridiq
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations
      python manage.py migrate
        python manage.py createsuperuser --noinput --email admin@viridiq.com --username admin --password $SUPERUSER_PASSWORD
    startCommand: python manage.py runserver 0.0.0.0:8000
    plan: free
