# Generated by Django 5.0.8 on 2024-08-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0002_remove_insurancecompany_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
