# Generated by Django 5.0.8 on 2024-08-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0003_claim_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplan',
            name='coverage_details',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='claims/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Insurance.claim')),
            ],
        ),
    ]
