# Generated by Django 5.0.8 on 2024-08-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
