# Generated by Django 5.0.8 on 2024-08-20 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_alter_client_otp'),
        ('Insurance', '0003_claim_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.insurancecompany')),
            ],
        ),
    ]
