# Generated by Django 5.0.8 on 2024-08-23 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_customtoken'),
        ('Insurance', '0004_alter_insuranceplan_coverage_details_claimdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarequest',
            old_name='request_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='company',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='request_data',
        ),
        migrations.AddField(
            model_name='datarequest',
            name='insurance_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.insurancecompany'),
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
