# Generated by Django 5.0.8 on 2024-08-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_rename_request_date_datarequest_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='data',
            field=models.TextField(),
        ),
    ]
