name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: viridiq-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build --build-arg EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }} \
                       --build-arg EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }} \
                       --build-arg EMAIL_FROM=${{ secrets.EMAIL_FROM }} \
                       --build-arg FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
                       --build-arg ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }} \
                       --build-arg SUPERUSER_PASSWORD=${{ secrets.SUPERUSER_PASSWORD }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/viridiqapi:latest
